# Generated by Django 4.0.5 on 2024-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=100, null=True)),
                ('Last_name', models.CharField(default='', max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100, null=True)),
                ('Mobile', models.BigIntegerField(default=1)),
                ('gender', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
