# Generated by Django 4.0.5 on 2024-01-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='uploads/category/')),
                ('product_name', models.CharField(default='', max_length=100, null=True)),
                ('product_price', models.IntegerField(default=1)),
                ('product_desc', models.CharField(default='', max_length=100, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.category')),
            ],
        ),
    ]
